### ISSUE TITLE
anyio is not optional

### ISSUE THREAD

**Issue by Ensber** [mark9064/factorio-rcon-py#2]
I was looking into reviving an older project, wehen i got this error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/niclas/workspace/factorioApi/factorio-rcon-py/factorio_rcon/__init__.py", line 1, in <module>
    from ._factorio_rcon import (
  File "/home/niclas/workspace/factorioApi/factorio-rcon-py/factorio_rcon/_factorio_rcon.py", line 407, in <module>
    class AsyncRCONClient(RCONSharedBase):
  File "/home/niclas/workspace/factorioApi/factorio-rcon-py/factorio_rcon/_factorio_rcon.py", line 433, in AsyncRCONClient
    rcon_socket: Optional[anyio.abc.SocketStream]
NameError: name 'anyio' is not defined
```

Looking through the code, it seems like anyio should have been a optional include.
Quick fix was to install anyio via: `pip install anyio`

**Comment by Berserker66** [comment]
Yep, can confirm, crashed stuff.

**Comment by mark9064** [comment]
Sorry about the breakage, caught me at the worst time possible (been off the grid for the week)
Release is yanked for now, pushing a patch ASAP

**Comment by mark9064** [comment]
Should be fixed with v2.0.1
